---
- name: Install common packages on all servers
  hosts: all
  become: true

  tasks:
    - name: Install bind-utils
      yum:
        name: bind-utils
        state: present

    - name: Install man
      yum:
        name: man
        state: present

    - name: Install man-pages
      yum:
        name: man-pages
        state: present

    - name: Install mlocate
      yum:
        name: mlocate
        state: present

    - name: Install Sysstat
      yum:
        name: sysstat
        state: present

    - name: Install vim
      yum:
        name: vim
        state: present

    - name: Install htop
      yum:
        name: htop
        state: present

    - name: Install net-tools
      yum:
        name: net-tools
        state: present