---
- name: Stop and disable firewall and SELinux on CentOS 7 and 8
  hosts: all
  become: true

  tasks:
    - name: Stop firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Disable firewalld at boot
      shell: "systemctl disable firewalld"
      when: ansible_distribution_major_version == "7"

    - name: Disable firewalld at boot (CentOS 8)
      shell: "systemctl disable --now firewalld"
      when: ansible_distribution_major_version == "8"

    - name: Set SELinux to permissive
      selinux:
        policy: targeted
        state: permissive