---
- name: Edit phpmyadmin.conf
  hosts: db9
  become: true

  tasks:
    - name: Backup original phpmyadmin.conf
      command: cp /etc/httpd/conf.d/phpMyAdmin.conf /etc/httpd/conf.d/phpMyAdmin.conf.bak
      ignore_errors: yes

    - name: Modify phpmyadmin.conf
      lineinfile:
        path: /etc/httpd/conf.d/phpMyAdmin.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^<RequireAny>', line: '<RequireAny>\n  Require ip 127.0.0.1\n  Require ip ::1\n  Require all granted' }
        - { regexp: 'Allow from 127.0.0.1', line: 'Allow from 127.0.0.1' }
        - { regexp: 'Allow from 192.168.130.0/23', line: 'Allow from 192.168.130.0/23' }

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
