---
- name: Install NRPE Client on CentOS 7
  hosts: all 
  become: true
  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install NRPE and plugins
      yum:
        name:
          - nrpe
          - nagios-plugins
        state: present

    - name: Configure NRPE
      template:
        src: nrpe.cfg.j2
        dest: /etc/nagios/nrpe.cfg
      notify: restart nrpe

  handlers:
    - name: restart nrpe
      service:
        name: nrpe
        state: restarted

