---
- name: Update Kernel and OS for CentOS
  hosts: ntp
  become: true

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Reboot if kernel was updated
      shell: "needs-restarting -r || echo 'No reboot required'"
      register: reboot_required
      changed_when: reboot_required.stdout != "No reboot required"

    - name: Wait for the system to reboot
      wait_for_connection:
        delay: 30
        timeout: 300
      when: reboot_required.changed

    - name: Verify if the system was updated successfully
      shell: "cat /etc/redhat-release"
      register: updated_release

    - name: Print updated OS version
      debug:
        var: updated_release.stdout