---
- name: Install Apache, PHP, and phpMyAdmin on CentOS 9
  hosts: db9
  become: true

  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: present

    - name: Start Apache service
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Install PHP
      dnf:
        name: php
        state: present

    - name: Create test.php file
      copy:
        content: |
          <?php
          // Show all information, defaults to INFO_ALL
          phpinfo();
          ?>
        dest: /var/www/html/test.php

    - name: Install phpMyAdmin
      dnf:
        name: phpMyAdmin
        state: present
        enablerepo: epel

  handlers:
    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted