---
- name: Create student user on CentOS 7 and 8 servers
  hosts: all
  become: true

  tasks:
    - name: Create the student user
      user:
        name: student
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Add student user to sudoers (optional)
      lineinfile:
        dest: /etc/sudoers
        line: 'student ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'