
---
- name: Install chrony and configure NTP servers
  hosts: all
  become: true

  tasks:
    - name: Install chrony package
      package:
        name: chrony
        state: present

    - name: Add NTP servers to chrony.conf
      lineinfile:
        path: /etc/chrony.conf
        line: |
          server 192.168.130.10 iburst
          server 192.168.130.11 iburst
        insertafter: '^pool .*'
     

  handlers:
    - name: Restart chrony
      service:
        name: chrony
        state: restarted

